Reformatted the folder layout to make new projects easier to add

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,11 +1,11 @@
 #!/bin/bash
 
 function print_usage() {
-    echo "Usage: $0 [-d] [-h] -f <assembly file>"
+    echo "Usage: $0 [-d] [-h] -f <folder name>"
     echo "Options:"
     echo "  -d   Remove the output file after execution"
     echo "  -h   Show this help message"
-    echo "  -f   Assembly file to be compiled"
+    echo "  -f   Folder name containing the assembly file to be compiled"
 }
 
 # check if there was nothing passed, print usage if true
@@ -19,7 +19,7 @@ while getopts ":f:hd" opt; do
     case $opt in
     f)
         ff=true
-        fn=$(echo $OPTARG | cut -f1 -d '.')
+        fn=$OPTARG
         ;;
     d)
         remove_output=true
@@ -41,8 +41,14 @@ if [[ $ff -ne true ]] || [ -z "$fn" ]; then
     exit 0
 fi
 
+# check if the specified folder exists, if not, print usage
+if [ ! -d "$fn" ]; then
+    echo "Error: $fn is not a valid directory"
+    exit 1
+fi
+
 # command to assemble file
-nasm -f elf64 -o "$fn.o" "$fn.asm" && ld -m elf_x86_64 -o "$fn" "$fn.o" && "./$fn"
+nasm -f elf64 -o "$fn/$fn.o" "$fn/main.asm" && ld -m elf_x86_64 -o "$fn/$fn" "$fn/$fn.o" && "$fn/$fn"
 
 # check if exit code is not zero, print it if true
 exit_code=$?
@@ -50,12 +56,12 @@ if [[ $exit_code -ne 0 ]]; then
     echo "Exit Code: $exit_code"
 fi
 
-rm "$fn.o"
+rm "$fn/$fn.o"
 
 if [[ $remove_output ]]; then
-    rm "$fn"
+    rm "$fn/$fn"
 else
     # move the output file to the Builds directory
     mkdir -p Builds
-    mv "$fn" Builds/
+    mv "$fn/$fn" Builds/
 fi
